# **MoE NN Dataset**
---

In [3]:
# ---------------------------------------------------
# Paths management
# ---------------------------------------------------
import os

# Project path
PROJECT_PATH = os.path.dirname(os.path.dirname(os.getcwd()))

if os.path.exists(PROJECT_PATH):
    print(f"PROJECT_PATH = {PROJECT_PATH}")
else:
    print(f"WARNING! PROJECT_PATH not found! = {PROJECT_PATH}")
    
# Data path
DATA_PATH = PROJECT_PATH + "/Data"
if os.path.exists(DATA_PATH):
    print(f"DATA_PATH = {DATA_PATH}")
else:
    print(f"WARNING! DATA_PATH not found! = {DATA_PATH}")

OUTPUT_DIR = DATA_PATH


# ---------------------------------------------------
# Used paths
# ---------------------------------------------------
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

PROJECT_PATH = /home/mambo/Documents/Aggregation-of-experts-for-day-ahead-time-series-forecasting
DATA_PATH = /home/mambo/Documents/Aggregation-of-experts-for-day-ahead-time-series-forecasting/Data

In [4]:
# ---------------------------------------------------
# Experts dataset
# ---------------------------------------------------
df_experts = pd.read_csv(DATA_PATH + "/experts.csv")

# Converts date to time format
df_experts["Date_Heure"] = pd.to_datetime(df_experts["Date_Heure"], errors="coerce")

# Remove unecessary data
cols_to_remove = ["ret_1", "ret_24", "vol_24", "mom_24", "hour_sin", "hour_cos"]
df_experts_clean = df_experts.drop(columns=cols_to_remove, errors="ignore")

print(f"Start date: {df_experts["Date_Heure"].min()}")
print(f"Stop date: {df_experts["Date_Heure"].max()}")
print(f"Samples : {len(df_experts["Date_Heure"])}")
#df_experts_clean.info()
df_experts_clean.head()

Start date: 2025-02-04 08:00:00
Stop date: 2025-11-22 23:00:00
Samples : 7000

           Date_Heure   y_true  randomforest         lgbm   elasticnet
0 2025-02-04 08:00:00  1711.92   1427.530996  1579.031619  1114.790411
1 2025-02-04 09:00:00  1644.14   1426.041510  1449.646301  1088.787479
2 2025-02-04 10:00:00  1542.14   1264.568898  1254.085201   983.225853
3 2025-02-04 11:00:00  1631.53   1234.265221  1242.456195   996.466808
4 2025-02-04 12:00:00  1583.82   1288.741372  1465.285302  1015.433340

In [5]:
# ---------------------------------------------------
# Features dataset
# ---------------------------------------------------
df_feat = pd.read_csv(DATA_PATH + "/data_engineering_belgique.csv")

# Converts date to time format
df_feat["Date_Heure"] = pd.to_datetime(df_feat["Date_Heure"], errors="coerce")
print(f"Start date: {df_feat["Date_Heure"].min()}")
print(f"Stop date: {df_feat["Date_Heure"].max()}")
print(f"Samples : {len(df_feat["Date_Heure"])}")
df_feat.info()
#df_feat.head()

Start date: 2018-01-02 00:00:00
Stop date: 2025-11-23 23:00:00
Samples : 68877
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68877 entries, 0 to 68876
Data columns (total 39 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Date_Heure                68877 non-null  datetime64[ns]
 1   Date_Heure.1              68877 non-null  object
 2   Eolien_MW                 68877 non-null  float64
 3   Offshore/onshore          68877 non-null  object
 4   Region                    68877 non-null  object
 5   speed_longitudinale_100m  68877 non-null  float64
 6   speed_latitudinale_100m   68877 non-null  float64
 7   speed_longitudinale_10m   68877 non-null  float64
 8   speed_latitudinale_10m    68877 non-null  float64
 9   2m_temperature            68877 non-null  float64
 10  mean_sea_level_pressure   68877 non-null  float64
 11  sea_surface_temperature   68877 non-null  float64
 12  surface_pressure          68877 non-null  float64
 13  Wind_Norm                 68877 non-null  float64
 14  Wind_Norm_10m             68877 non-null  float64
 15  Wind_Norm_Cubes           68877 non-null  float64
 16  Wind_Norm_Cubes_10m       68877 non-null  float64
 17  Wind_mean_3h              68877 non-null  float64
 18  wind_std_3h               68877 non-null  float64
 19  wind_cv_3h                68877 non-null  float64
 20  Wind_mean_3h_10m          68877 non-null  float64
 21  wind_std_3h_10m           68877 non-null  float64
 22  wind_cv_3h_10m            68877 non-null  float64
 23  Wind_Dir_Meteo_sin        68877 non-null  float64
 24  Wind_Dir_Meteo_cos        68877 non-null  float64
 25  Wind_Dir_Meteo_sin_10m    68877 non-null  float64
 26  Wind_Dir_Meteo_cos_10m    68877 non-null  float64
 27  Air_density               68877 non-null  float64
 28  Y_lag_1h                  68877 non-null  float64
 29  Y_lag_24h                 68877 non-null  float64
 30  Wind_Norm_lag_1h          68877 non-null  float64
 31  Wind_Norm_lag_24h         68877 non-null  float64
 32  Hour_sin                  68877 non-null  float64
 33  Hour_cos                  68877 non-null  float64
 34  Weekday_sin               68877 non-null  float64
 35  Weekday_cos               68877 non-null  float64
 36  Month_sin                 68877 non-null  float64
 37  Month_cos                 68877 non-null  float64
 38  P_curve                   68877 non-null  float64
dtypes: datetime64[ns](1), float64(35), object(3)
memory usage: 20.5+ MB

In [6]:
# ---------------------------------------------------
# Merge based on "Date_et_Heure"
# ---------------------------------------------------
features = [
    "Date_Heure",
    "Wind_Norm",
    "Wind_Norm_Cubes",
    "wind_cv_3h",
    "Wind_Dir_Meteo_sin",
    "Wind_Dir_Meteo_cos",
    "Air_density",
    "Hour_sin",
    "Hour_cos",
    "Month_sin",
    "Month_cos"
]

# Merge based on "Date_Heure"
df_merged = df_experts_clean.merge(
    df_feat[features],
    on="Date_Heure",
    how="left"
)

df_merged.to_csv(f"{OUTPUT_DIR}/experts_and_features_for_moe_nn_01.csv")

print(f"Start date: {df_merged["Date_Heure"].min()}")
print(f"Stop date: {df_merged["Date_Heure"].max()}")
print(f"Samples : {len(df_merged["Date_Heure"])}")
df_merged.info()
df_merged.head()

Start date: 2025-02-04 08:00:00
Stop date: 2025-11-22 23:00:00
Samples : 7000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7000 entries, 0 to 6999
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date_Heure          7000 non-null   datetime64[ns]
 1   y_true              7000 non-null   float64
 2   randomforest        7000 non-null   float64
 3   lgbm                7000 non-null   float64
 4   elasticnet          7000 non-null   float64
 5   Wind_Norm           7000 non-null   float64
 6   Wind_Norm_Cubes     7000 non-null   float64
 7   wind_cv_3h          7000 non-null   float64
 8   Wind_Dir_Meteo_sin  7000 non-null   float64
 9   Wind_Dir_Meteo_cos  7000 non-null   float64
 10  Air_density         7000 non-null   float64
 11  Hour_sin            7000 non-null   float64
 12  Hour_cos            7000 non-null   float64
 13  Month_sin           7000 non-null   float64
 14  Month_cos           7000 non-null   float64
dtypes: datetime64[ns](1), float64(14)
memory usage: 820.4 KB

,Date_Heure,y_true,randomforest,lgbm,elasticnet,Wind_Norm,Wind_Norm_Cubes,wind_cv_3h,Wind_Dir_Meteo_sin,Wind_Dir_Meteo_cos,Air_density,Hour_sin,Hour_cos,Month_sin,Month_cos
0,2025-02-04 08:00:00,1711.92,1427.530996,1579.031619,1114.790411,11.292508,1440.028953,0.027057,-0.975150,-0.221547,1.283743,8.660254e-01,-0.500000,0.866025,0.5
1,2025-02-04 09:00:00,1644.14,1426.041510,1449.646301,1088.787479,11.168246,1393.012077,0.006363,-0.984154,-0.177317,1.285232,7.071068e-01,-0.707107,0.866025,0.5
2,2025-02-04 10:00:00,1542.14,1264.568898,1254.085201,983.225853,10.631959,1201.821141,0.031823,-0.975354,-0.220648,1.291218,5.000000e-01,-0.866025,0.866025,0.5
3,2025-02-04 11:00:00,1631.53,1234.265221,1242.456195,996.466808,10.631505,1201.667152,0.028653,-0.985868,-0.167523,1.291403,2.588190e-01,-0.965926,0.866025,0.5
4,2025-02-04 12:00:00,1583.82,1288.741372,1465.285302,1015.433340,10.745383,1240.696997,0.006150,-0.991743,-0.128239,1.290729,1.224647e-16,-1.000000,0.866025,0.5